export const ScenarioList= [
	{
				scenarioId: "1-A",
				title: "List BlockedUsers(all, global)",
				description:
					"Lists user blocks with filters via GET /user-blocks/listUserBlocks.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/listUserBlocks",
				requestPayload: null,
				checklistItems: [
					"Validate pagination limit/nextToken",
					"Filter by from/to/scope and ensure results match",
					"Confirm count matches returned items length",
				],
				inputFields: [
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "",
					},
					{
						type: "text",
						id: "flag",
						label: "Flag",
						placeholder: "manual",
						value: "",
					},
					{
						type: "select",
						id: "permanent",
						label: "Permanent",
						options: [
							{ value: "", text: "global" },
							{ value: "true", text: "True" },
							{ value: "false", text: "False" },
						],
					},
					{
						type: "text",
						id: "limit",
						label: "Limit",
						placeholder: "20",
						value: "20",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "nextToken",
						label: "Next Token",
						placeholder: "token",
						value: "",
					},
				],
			},
			{
				scenarioId: "1-B",
				title: "List BlockedUsers (Scoped)",
				description:
					"Lists user blocks filtered by scope ('feed', 'private_chat', 'global' ).",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/listUserBlocks",
				requestPayload: null,
				checklistItems: ["Verify all returned items have scope 'feed'"],
				inputFields: [
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "private_chat",
						required: true,
					},
					{
						type: "text",
						id: "limit",
						label: "Limit",
						placeholder: "20",
						value: "20",
						inputMode: "numeric",
					},
				],
			},
			{
				scenarioId: "1-C",
				title: "Get Blocks For User",
				description:
					"Retrieves blocks for a specific user via GET /user-blocks/getBlocksForUser.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/getBlocksForUser",
				requestPayload: null,
				checklistItems: [
					"Returns active records by default",
					"When show_deleted is true, includes soft-deleted rows",
				],
				inputFields: [
					{
						type: "text",
						id: "to",
						label: "Blocked User ID",
						placeholder: "user id",
						required: true,
					},
					{
						type: "select",
						id: "show_deleted",
						label: "Show Deleted",
						options: [
							{ value: "false", text: "No (default)" },
							{ value: "true", text: "Yes" },
						],
						value: "false",
					},
				],
			},

		// <!-- Block Actions -->

{
				scenarioId: "2-A",
				title: "User to User - Block User (SCOPED Permanent)",
				description: "Blocks a user specifically in the 'feed' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockUser",
				requestPayload: {
					from: "user_a",
					to: "user_b",
					scope: "feed",
					is_permanent: true,
				},
				checklistItems: [
					"Verify scope is correctly recorded as 'feed'",
					"Ensure this does not affect 'chat' scope if scopes are independent",
				],
				inputFields: [
					{
						type: "text",
						id: "from",
						required: true,
						label: "From",
						value: "user_a",
					},
					{
						type: "text",
						id: "to",
						required: true,
						label: "To",
						value: "user_b",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "private_chat",
						required: true,
					},
				],
			},
			{
				scenarioId: "2-B",
				title: "User to User - Block User (SCOPED Temporary)",
				description:
					"Blocks a user specifically in the 'private_chat' (dm) scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockUser",
				requestPayload: {
					from: "user_a",
					to: "user_b",
					scope: "private_chat",
					is_permanent: false,
					expires_at: 86000,
				},
				checklistItems: [
					"Verify scope is correctly recorded as 'private_chat'",
					"Ensure this does not affect 'feed' scope",
				],
				inputFields: [
					{
						type: "text",
						id: "from",
						required: true,
						label: "From",
						value: "user_a",
					},
					{
						type: "text",
						id: "to",
						required: true,
						label: "To",
						value: "user_b",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "global", text: "Global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "private_chat",
						required: true,
					},
					{
						type: "text",
						id: "expires_at",
						required: true,
						label: "expires_at",
						value: "86000",
					},
				],
			},
			{
				scenarioId: "2-C",
				title: "System to User - Block User (SCOPED)",
				description:
					"Blocks a user specifically in the 'private_chat' (dm) scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockUser",
				requestPayload: {
					from: "user_a",
					to: "system",
					scope: "private_chat",
					is_permanent: false,
					expires_at: 86000,
				},
				checklistItems: [
					"Verify scope is correctly recorded as 'private_chat'",
					"Ensure this does not affect 'feed' scope",
				],
				inputFields: [
					{
						type: "text",
						id: "from",
						required: true,
						label: "From",
						value: "user_a",
					},
					{
						type: "text",
						id: "to",
						required: true,
						label: "To",
						value: "system",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "global", text: "Global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "private_chat",
						required: true,
					},
					{
						type: "text",
						id: "expires_at",
						required: true,
						label: "expires_at",
						value: "86000",
					},
				],
			},
		
		// <!-- Unblock Actions -->
					
		{
				scenarioId: "3-A",
				title: "User to User - Unblock (Scoped)",
				description: "Unblocks a user specifically in the  scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/unblockUser",
				requestPayload: {
					from: "user_a",
					to: "user_b",
					scope: "feed",
				},
				checklistItems: [
					"Verify 'feed' block is removed",
					"Verify other scopes remain if they existed",
				],
				inputFields: [
					{
						type: "text",
						id: "from",
						required: true,
						label: "From",
						value: "user_a",
					},
					{
						type: "text",
						id: "to",
						required: true,
						label: "To",
						value: "user_b",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "private_chat",
						required: true,
					},
				],
			},
			{
				scenarioId: "3-B",
				title: "User to User - Unblock (Scoped, Non-Existent)",
				description:
					"Attempts to unblock a user pair that is not blocked (Feed scope).",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/unblockUser",
				requestPayload: {
					from: "user_x",
					to: "user_y",
					scope: "feed",
				},
				checklistItems: [
					"Ideally should be idempotent (success or 404, not 500)",
					"Confirm no ghost entries created",
				],
				inputFields: [
					{
						type: "text",
						id: "from",
						required: true,
						label: "From",
						value: "user_x",
					},
					{
						type: "text",
						id: "to",
						required: true,
						label: "To",
						value: "user_y",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "feed",
						required: true,
					},
				],
			},
{
				scenarioId: "3-C",
				title: "System to User - Unblock (Scoped)",
				description: "Unblocks a user specifically in the  scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/unblockUser",
				requestPayload: {
					from: "system",
					to: "user_b",
					scope: "feed",
				},
				checklistItems: [
					"Verify 'feed' block is removed",
					"Verify other scopes remain if they existed",
				],
				inputFields: [
					{
						type: "text",
						id: "from",
						required: true,
						label: "From",
						value: "system",
					},
					{
						type: "text",
						id: "to",
						required: true,
						label: "To",
						value: "user_b",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "private_chat",
						required: true,
					},
				],
			},

		// <!-- Check Actions -->
					
		{
				scenarioId: "4-A",
				title: "User to User - Is Blocked (Scoped)",
				description: "Checks block status specifically for 'feed' scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isUserBlocked",
				requestPayload: null,
				checklistItems: ["Confirm result reflects feed block status"],
				inputFields: [
					{
						type: "text",
						id: "from",
						required: true,
						label: "From",
						value: "user_a",
					},
					{
						type: "text",
						id: "to",
						required: true,
						label: "To",
						value: "user_b",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "Global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "feed",
						required: true,
					},
				],
			},
		{
				scenarioId: "4-B",
				title: "System to User - Is Blocked (Scoped)",
				description: "Checks block status specifically for 'feed' scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isUserBlocked",
				requestPayload: null,
				checklistItems: ["Confirm result reflects feed block status"],
				inputFields: [
					{
						type: "text",
						id: "from",
						required: true,
						label: "From",
						value: "system",
					},
					{
						type: "text",
						id: "to",
						required: true,
						label: "To",
						value: "user_b",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "Global" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat (DM)" },
						],
						value: "feed",
						required: true,
					},
				],
			},
			{
				scenarioId: "5",
				title: "User to User - Batch Check (all, global Scopes)",
				description:
					"Batch check multiple pairs via POST /user-blocks/batchCheckUserBlocks.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/batchCheckUserBlocks",
				requestPayload: {
					blocks: [
						{ from: "user_a", to: "user_b", scope: "feed" },
						{ from: "user_c", to: "user_d", scope: "private_chat" },
					],
				},
				checklistItems: [
					"Confirm array validation returns 400 when blocks is not an array",
					"Verify per-item results align with single check endpoint",
					"Test mixed blocked/unblocked cases",
				],
				inputFields: [],
			},

		// <!-- System Blocks -->

			{
				scenarioId: "6-A",
				title: "System - List System Blocks(all/ global scopes)",
				description:
					"Lists system blocks with filters via GET /user-blocks/listSystemBlocks.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/listSystemBlocks",
				requestPayload: null,
				checklistItems: [
					"Validate pagination and filters (ip, flag, permanent, scope)",
					"Confirm count matches items length",
				],
				inputFields: [
					{
						type: "text",
						id: "ip",
						label: "IP",
						placeholder: "203.0.113.10",
						value: "",
					},
					{
						type: "text",
						id: "flag",
						label: "Flag",
						placeholder: "manual",
						value: "",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "global" },
							{ value: "auth", text: "Auth" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat" },
						],
						value: "",
					},
					{
						type: "text",
						id: "reason",
						label: "Reason",
						placeholder: "fraud",
						value: "",
					},
					{
						type: "select",
						id: "permanent",
						label: "Permanent",
						options: [
							{ value: "", text: "global" },
							{ value: "true", text: "True" },
							{ value: "false", text: "False" },
						],
					},
					{
						type: "text",
						id: "limit",
						label: "Limit",
						placeholder: "20",
						value: "20",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "nextToken",
						label: "Next Token",
						placeholder: "token",
						value: "",
					},
				],
			},
			{
				scenarioId: "6-B",
				title: "System - List System Blocks (Scoped)",
				description: "Lists system blocks filtered by scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/listSystemBlocks",
				requestPayload: null,
				checklistItems: ["Verify all returned items have scope 'auth'"],
				inputFields: [
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "", text: "global" },
							{ value: "feed", text: "Feed" },
							{
								value: "private_chat",
								text: "Private Chat (DM)",
							},
						],
						value: "private_chat",
						required: true,
					},
					{
						type: "text",
						id: "limit",
						label: "Limit",
						placeholder: "20",
						value: "20",
						inputMode: "numeric",
					},
				],
			},
			{
				scenarioId: "7-A",
				title: "System - Block IP (Auth Permanent)",
				description: "Blocks an IP in the 'auth' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockIP",
				requestPayload: {
					ip: "203.0.113.10",
					scope: "auth",
					is_permanent: true,
				},
				checklistItems: ["Verify scope is correctly recorded as 'auth'"],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "auth",
					},
				],
			},
			{
				scenarioId: "7-B",
				title: "System - Block IP (Feed Permanent)",
				description: "Blocks an IP in the 'feed' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockIP",
				requestPayload: {
					ip: "203.0.113.10",
					scope: "feed",
					is_permanent: true,
				},
				checklistItems: ["Verify scope is correctly recorded as 'feed'"],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "feed",
					},
				],
			},

			{
				scenarioId: "7-C",
				title: "System - Block IP (Private Chat Permanent)",
				description: "Blocks an IP in the 'private_chat' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockIP",
				requestPayload: {
					ip: "203.0.113.10",
					scope: "private_chat",
					is_permanent: true,
				},
				checklistItems: [
					"Verify scope is correctly recorded as 'private_chat'",
				],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "private_chat",
					},
				],
			},
			{
				scenarioId: "7-D",
				title: "System - Block IP (Auth Temporary)",
				description: "Temporarily blocks an IP in the 'auth' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockIP",
				requestPayload: {
					ip: "203.0.113.10",
					scope: "auth",
					is_permanent: false,
					expires_at: 86400,
				},
				checklistItems: ["Verify IP block expires after ~24 hours"],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "auth", text: "Auth" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat" },
						],
						value: "auth",
						required: true,
					},
					{
						type: "select",
						id: "permanent",
						label: "Permanent",
						options: [
							{ value: "false", text: "False" },
							{ value: "true", text: "True" },
						],
						value: "false",
						required: true,
					},
					{
						type: "text",
						id: "temporary",
						label: "Temporary (seconds)",
						placeholder: "86400",
						value: "86400",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "expiresAt",
						label: "Expires At (optional)",
						placeholder: "Pick date/time below",
						typeOverride: "datetime-local",
					},
				],
			},

			{
				scenarioId: "7-E",
				title: "System - Block IP (Feed Temporary)",
				description: "Temporarily blocks an IP in the 'feed' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockIP",
				requestPayload: {
					ip: "203.0.113.10",
					scope: "feed",
					is_permanent: false,
					expires_at: 86400,
				},
				checklistItems: ["Verify IP block expires after ~24 hours"],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "auth", text: "Auth" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat" },
						],
						value: "feed",
						required: true,
					},
					{
						type: "select",
						id: "permanent",
						label: "Permanent",
						options: [
							{ value: "false", text: "False" },
							{ value: "true", text: "True" },
						],
						value: "false",
						required: true,
					},
					{
						type: "text",
						id: "temporary",
						label: "Temporary (seconds)",
						placeholder: "86400",
						value: "86400",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "expiresAt",
						label: "Expires At (optional)",
						placeholder: "Pick date/time below",
						typeOverride: "datetime-local",
					},
				],
			},

			{
				scenarioId: "7-F",
				title: "System - Block IP (Private Chat Temporary)",
				description: "Temporarily blocks an IP in the 'private_chat' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockIP",
				requestPayload: {
					ip: "203.0.113.10",
					scope: "private_chat",
					is_permanent: false,
					expires_at: 86400,
				},
				checklistItems: ["Verify IP block expires after ~24 hours"],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "auth", text: "Auth" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat" },
						],
						value: "private_chat",
						required: true,
					},
					{
						type: "select",
						id: "permanent",
						label: "Permanent",
						options: [
							{ value: "false", text: "False" },
							{ value: "true", text: "True" },
						],
						value: "false",
						required: true,
					},
					{
						type: "text",
						id: "temporary",
						label: "Temporary (seconds)",
						placeholder: "86400",
						value: "86400",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "expiresAt",
						label: "Expires At (optional)",
						placeholder: "Pick date/time below",
						typeOverride: "datetime-local",
					},
				],
			},

			{
				scenarioId: "8-A",
				title: "System - Is IP Blocked (Auth)",
				description: "Checks if IP is blocked in 'auth' scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isIPBlocked",
				requestPayload: null,
				checklistItems: ["Confirm result reflects auth block status"],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "auth",
					},
				],
			},

			{
				scenarioId: "8-B",
				title: "System - Is IP Blocked (Feed)",
				description: "Checks if IP is blocked in 'feed' scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isIPBlocked",
				requestPayload: null,
				checklistItems: ["Confirm result reflects feed block status"],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "feed",
					},
				],
			},

			{
				scenarioId: "8-C",
				title: "System - Is IP Blocked (Private Chat)",
				description: "Checks if IP is blocked in 'private_chat' scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isIPBlocked",
				requestPayload: null,
				checklistItems: ["Confirm result reflects private_chat block status"],
				inputFields: [
					{
						type: "text",
						id: "ip",
						required: true,
						label: "IP",
						value: "203.0.113.10",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "private_chat",
					},
				],
			},

			{
				scenarioId: "9-A",
				title: "System - Block Email (Auth Permanent)",
				description: "Blocks an email in the 'auth' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockEmail",
				requestPayload: {
					email: "test@example.com",
					scope: "auth",
					is_permanent: true,
				},
				checklistItems: ["Verify scope is correctly recorded as 'auth'"],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "auth",
					},
				],
			},

			{
				scenarioId: "9-B",
				title: "System - Block Email (Feed Permanent)",
				description: "Blocks an email in the 'feed' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockEmail",
				requestPayload: {
					email: "test@example.com",
					scope: "feed",
					is_permanent: true,
				},
				checklistItems: ["Verify scope is correctly recorded as 'feed'"],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "feed",
					},
				],
			},

			{
				scenarioId: "9-C",
				title: "System - Block Email (Private Chat Permanent)",
				description: "Blocks an email in the 'private_chat' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockEmail",
				requestPayload: {
					email: "test@example.com",
					scope: "private_chat",
					is_permanent: true,
				},
				checklistItems: [
					"Verify scope is correctly recorded as 'private_chat'",
				],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "private_chat",
					},
				],
			},

			{
				scenarioId: "9-D",
				title: "System - Block Email (Auth Temporary)",
				description: "Temporarily blocks an email in the 'auth' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockEmail",
				requestPayload: {
					email: "test@example.com",
					scope: "auth",
					is_permanent: false,
					expires_at: 86400,
				},
				checklistItems: ["Verify email block expires after ~24 hours"],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "auth", text: "Auth" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat" },
						],
						value: "auth",
						required: true,
					},
					{
						type: "select",
						id: "permanent",
						label: "Permanent",
						options: [
							{ value: "false", text: "False" },
							{ value: "true", text: "True" },
						],
						value: "false",
						required: true,
					},
					{
						type: "text",
						id: "temporary",
						label: "Temporary (seconds)",
						placeholder: "86400",
						value: "86400",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "expiresAt",
						label: "Expires At (optional)",
						placeholder: "Pick date/time below",
						typeOverride: "datetime-local",
					},
				],
			},

			{
				scenarioId: "9-E",
				title: "System - Block Email (Feed Temporary)",
				description: "Temporarily blocks an email in the 'feed' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockEmail",
				requestPayload: {
					email: "test@example.com",
					scope: "feed",
					is_permanent: false,
					expires_at: 86400,
				},
				checklistItems: ["Verify email block expires after ~24 hours"],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "auth", text: "Auth" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat" },
						],
						value: "feed",
						required: true,
					},
					{
						type: "select",
						id: "permanent",
						label: "Permanent",
						options: [
							{ value: "false", text: "False" },
							{ value: "true", text: "True" },
						],
						value: "false",
						required: true,
					},
					{
						type: "text",
						id: "temporary",
						label: "Temporary (seconds)",
						placeholder: "86400",
						value: "86400",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "expiresAt",
						label: "Expires At (optional)",
						placeholder: "Pick date/time below",
						typeOverride: "datetime-local",
					},
				],
			},

			{
				scenarioId: "9-F",
				title: "System - Block Email (Private Chat Temporary)",
				description:
					"Temporarily blocks an email in the 'private_chat' scope.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/blockEmail",
				requestPayload: {
					email: "test@example.com",
					scope: "private_chat",
					is_permanent: false,
					expires_at: 86400,
				},
				checklistItems: ["Verify email block expires after ~24 hours"],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "select",
						id: "scope",
						label: "Scope",
						options: [
							{ value: "auth", text: "Auth" },
							{ value: "feed", text: "Feed" },
							{ value: "private_chat", text: "Private Chat" },
						],
						value: "private_chat",
						required: true,
					},
					{
						type: "select",
						id: "permanent",
						label: "Permanent",
						options: [
							{ value: "false", text: "False" },
							{ value: "true", text: "True" },
						],
						value: "false",
						required: true,
					},
					{
						type: "text",
						id: "temporary",
						label: "Temporary (seconds)",
						placeholder: "86400",
						value: "86400",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "expiresAt",
						label: "Expires At (optional)",
						placeholder: "Pick date/time below",
						typeOverride: "datetime-local",
					},
				],
			},

			{
				scenarioId: "10-A",
				title: "System - Is Email Blocked (Auth)",
				description: "Checks if email is blocked in 'auth' scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isEmailBlocked",
				requestPayload: null,
				checklistItems: ["Confirm result reflects auth block status"],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "auth",
					},
				],
			},

			{
				scenarioId: "10-B",
				title: "System - Is Email Blocked (Feed)",
				description: "Checks if email is blocked in 'feed' scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isEmailBlocked",
				requestPayload: null,
				checklistItems: ["Confirm result reflects feed block status"],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "feed",
					},
				],
			},

			{
				scenarioId: "10-C",
				title: "System - Is Email Blocked (Private Chat)",
				description: "Checks if email is blocked in 'private_chat' scope.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isEmailBlocked",
				requestPayload: null,
				checklistItems: ["Confirm result reflects private_chat block status"],
				inputFields: [
					{
						type: "text",
						id: "email",
						required: true,
						label: "Email",
						value: "test@example.com",
					},
					{
						type: "text",
						id: "scope",
						required: true,
						label: "Scope",
						value: "private_chat",
					},
				],
			},

				// <!-- Manual Action -->

			{
				scenarioId: "11",
				title: "Manual Action - List Manual Actions(all, paginated)",
				description:
					"Lists manual actions with filters via GET /user-blocks/listManualActions.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/listManualActions",
				requestPayload: null,
				checklistItems: [
					"Validate filters (userId/adminId/flagKey) affect results",
					"Confirm pagination behavior",
				],
				inputFields: [
					{
						type: "text",
						id: "userId",
						label: "User ID",
						placeholder: "user id",
						value: "",
					},
					{
						type: "text",
						id: "adminId",
						label: "Admin ID",
						placeholder: "admin id",
						value: "",
					},
					{
						type: "text",
						id: "flagKey",
						label: "Flag Key",
						placeholder: "warning_low",
						value: "",
					},
					{
						type: "text",
						id: "limit",
						label: "Limit",
						placeholder: "20",
						value: "20",
						inputMode: "numeric",
					},
					{
						type: "text",
						id: "nextToken",
						label: "Next Token",
						placeholder: "token",
						value: "",
					},
				],
			},

			{
				scenarioId: "12-A",
				title: "Manual Action - Suspend User",
				description: "Suspends a user via POST /user-blocks/suspendUser.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/suspendUser",
				requestPayload: {
					userId: "user_sus_1",
					reason: "tos_violation",
					adminId: "admin_1",
					flag: "manual",
					note: "investigate",
				},
				checklistItems: [
					"Confirm required userId/reason/adminId validation",
					"Validate suspension recorded with flag and note",
					"Check subsequent isUserSuspended reflects true",
				],
				inputFields: [
					{
						type: "text",
						id: "userId",
						required: true,
						label: "User ID",
						placeholder: "user id",
						value: "user_sus_1",
					},
					{
						type: "text",
						id: "reason",
						required: true,
						label: "Reason",
						placeholder: "tos_violation",
						value: "tos_violation",
					},
					{
						type: "text",
						id: "adminId",
						required: true,
						label: "Admin ID",
						placeholder: "admin id",
						value: "admin_1",
					},
					{
						type: "text",
						id: "flag",
						label: "Flag",
						placeholder: "manual",
						value: "manual",
					},
					{
						type: "text",
						id: "note",
						label: "Note",
						placeholder: "Notes for suspension",
						value: "investigate",
					},
				],
			},

			{
				scenarioId: "12-B",
				title: "Manual Action - Suspend (Duplicate)",
				description:
					"Attempts to suspend an already suspended user to test idempotency/update behavior.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/suspendUser",
				requestPayload: {
					userId: "user_sus_1",
					reason: "updated_reason",
					adminId: "admin_1",
				},
				checklistItems: [
					"Ideally should update the existing suspension or return success",
					"Verify reason is updated in manual actions list",
				],
				inputFields: [
					{
						type: "text",
						id: "userId",
						required: true,
						label: "User ID",
						value: "user_sus_1",
					},
					{
						type: "text",
						id: "reason",
						required: true,
						label: "Reason",
						value: "updated_reason",
					},
					{
						type: "text",
						id: "adminId",
						required: true,
						label: "Admin ID",
						value: "admin_1",
					},
				],
			},

			{
				scenarioId: "13",
				title: "Manual Action - Unsuspend User",
				description: "Unsuspends a user via POST /user-blocks/unsuspendUser.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/unsuspendUser",
				requestPayload: {
					userId: "user_sus_1",
				},
				checklistItems: [
					"Confirm user returns to active state",
					"Validate idempotent behavior when not suspended",
				],
				inputFields: [
					{
						type: "text",
						id: "userId",
						required: true,
						label: "User ID",
						placeholder: "user id",
						value: "user_sus_1",
					},
				],
			},

			{
				scenarioId: "14",
				title: "Manual Action - Is User Suspended",
				description:
					"Checks suspension status via GET /user-blocks/isUserSuspended.",
				apiMethod: "GET",
				apiEndpoint: "/user-blocks/isUserSuspended",
				requestPayload: null,
				checklistItems: [
					"Validate suspended boolean matches suspension table",
					"Confirm details payload present when suspended",
				],
				inputFields: [
					{
						type: "text",
						id: "userId",
						required: true,
						label: "User ID",
						placeholder: "user id",
						value: "user_sus_1",
					},
				],
			},

			{
				scenarioId: "15",
				title: "Manual Action - Warn User",
				description: "Warns a user via POST /user-blocks/warnUser.",
				apiMethod: "POST",
				apiEndpoint: "/user-blocks/warnUser",
				requestPayload: {
					userId: "user_warn_1",
					flagKey: "warning_low",
					adminId: "admin_1",
					note: "first warning",
				},
				checklistItems: [
					"Confirm required userId/flagKey/adminId validation",
					"Validate warning stored and visible in manual actions",
				],
				inputFields: [
					{
						type: "text",
						id: "userId",
						required: true,
						label: "User ID",
						placeholder: "user id",
						value: "user_warn_1",
					},
					{
						type: "text",
						id: "flagKey",
						required: true,
						label: "Flag Key",
						placeholder: "warning_low",
						value: "warning_low",
					},
					{
						type: "text",
						id: "adminId",
						required: true,
						label: "Admin ID",
						placeholder: "admin id",
						value: "admin_1",
					},
					{
						type: "text",
						id: "note",
						label: "Note",
						placeholder: "first warning",
						value: "first warning",
					},
				],
			}
		];
			